name: Metrics

# Controls when the workflow will run
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push:
    branches: [ main ]
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Core
          user: adiletelf
          config_timezone: Asia/Tomsk
          commiter_message: "chore: update metrics"
          
          # Display
          template: classic
          base: header, activity, community, repositories
          
          # Plugins
          # plugin_introduction: yes
          plugin_languages: yes
          plugin_activity: yes
          
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          
